workspace = { members = ["lib/macros"] }
[package]
name = "strawberryvm"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "addition"

[[bin]]
name = "asm"

[[bin]]
name = "machine"

[dependencies.macros]
path = "lib/macros"
